tasks:
  - name: Spin up Dev env
    init: |
      yarn install
    command: |
      yarn start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - synedra.auto-run-command
