tasks:
  - name: Spin up Dev env
    init: |
      yarn install
      npm install nodemon -g

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - synedra.auto-run-command
